### ISSUE TITLE
MacOS (big sur, x86) doesn't work with following error:

### ISSUE THREAD

**Issue by ityonemo** [ityonemo/zigler#236]
```
unexpected LLD stderr:
l64.lld: error: unable to find library for -lSystem
```

**Comment by rodrigues** [comment]
Hey @ityonemo, thanks for the suggestions, still no luck haha, just sharing some more info. Also manage to reproduce the same behaviour in my iMac, which is also on BigSur.

```shell
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
```

It looks to me that zig knows where to find XCode's libc though.

```shell
/Users/rodrigues/code/benchin/deps/zigler/zig/zig-macos-x86_64-0.7.1/zig libc
# The directory that contains `stdlib.h`.
# On POSIX-like systems, include directories be found with: `cc -E -Wp,-v -xc /dev/null`
include_dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

# The system-specific include directory. May be the same as `include_dir`.
# On Windows it's the directory that includes `vcruntime.h`.
# On POSIX it's the directory that includes `sys/errno.h`.
sys_include_dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

# …
````

Wish zig could tell me a bit more about the error. as build.zig is there at this folder and it knows libc include path:

```shell
.zigler_compiler/dev/Elixir.Ziggy via ↯ v0.7.1 
❯ /Users/rodrigues/code/benchin/deps/zigler/zig/zig-macos-x86_64-0.7.1/zig build --verbose
error: FileNotFound
```

Passing as a reference the full error, with a `IO.inspect()` call just before calling the executable:

```
Compiling 1 file (.ex)

15:53:53.265 [warn]  macos support is experimental

15:53:53.296 [debug] compiling nif for module Ziggy in path /var/folders/h_/0bzb9mk979x57yqyqz35k7c80000gn/T/.zigler_compiler/dev/Elixir.Ziggy

15:53:53.341 [debug] wrote build.zig to /var/folders/h_/0bzb9mk979x57yqyqz35k7c80000gn/T/.zigler_compiler/dev/Elixir.Ziggy/build.zig
{:zigggin,
 [
   compiler: %Zig.Compiler{
     assembly: [],
     assembly_dir: "/var/folders/h_/0bzb9mk979x57yqyqz35k7c80000gn/T/.zigler_compiler/dev/Elixir.Ziggy",
     code_file: "/var/folders/h_/0bzb9mk979x57yqyqz35k7c80000gn/T/.zigler_compiler/dev/Elixir.Ziggy/Elixir.Ziggy.zig",
     compiler_target: :host,
     module_spec: %Zig.Module{
       c_includes: [],
       code: [[], [],
        "// ref: /Users/rodrigues/code/benchin/lib/ziggy.ex line: 4\n",
        "/// nif: ziggy_square/1\nfn ziggy_square(item: i64) i64 {\n  return item * item;\n}",
        "\n"],
       dry_run: false,
       file: "/Users/rodrigues/code/benchin/lib/ziggy.ex",
       imports: [std: "std", e: "erl_nif.zig", beam: "beam.zig"],
       include_dirs: [],
       libs: [],
       link_libc: false,
       local_zig: false,
       module: Ziggy,
       nifs: [
         %Zig.Parser.Nif{
           args: ["i64"],
           arity: 1,
           doc: nil,
           name: :ziggy_square,
           opts: [],
           retval: "i64",
           test: nil
         }
       ],
       otp_app: :benchin,
       resources: [],
       system_include_dirs: [],
       test_dirs: nil,
       version: #Version<0.1.0>,
       zig_file: "",
       zig_version: #Version<0.7.1>
     },
     test_dirs: []
   },
   opts: [
     cd: "/var/folders/h_/0bzb9mk979x57yqyqz35k7c80000gn/T/.zigler_compiler/dev/Elixir.Ziggy",
     stderr_to_stdout: true
   ],
   zig_executable: "/Users/rodrigues/code/benchin/deps/zigler/zig/zig-macos-x86_64-0.7.1/zig",
   zig_tree: "/Users/rodrigues/code/benchin/deps/zigler/zig/zig-macos-x86_64-0.7.1"
 ]}

== Compilation error in file lib/ziggy.ex ==
** (CompileError)  this zig compiler warning hasn't been incorporated into the parser.
Please file a report at:
https://github.com/ityonemo/zigler/issues
warning: unexpected LLD stderr:
ld64.lld: error: Unable to find library for -lSystem

error: FileNotFound

    (zigler 0.7.2) lib/zig/parser/error.ex:54: Zig.Parser.Error.parse/2
    (zigler 0.7.2) lib/zig/command.ex:37: Zig.Command.compile/2
    (zigler 0.7.2) lib/zig/compiler.ex:102: Zig.Compiler.compilation/2
    (zigler 0.7.2) expanding macro: Zig.Compiler.__before_compile__/1
    lib/ziggy.ex:1: Ziggy (module)
```

**Comment by garretttaco** [comment]
Are there any workarounds on this for the time being? I tried `local_zig: true` since zig works on my machine, but that made no difference.

**Comment by ityonemo** [comment]
I don't but if you figure something out a PR would be appreciated =D.  I'm planning on working on this once Zig 0.8.0 hits (circa 2-3 weeks?)...  I am ready... with sosumi on my laptop and a CI strategy.

**Comment by ityonemo** [comment]
macos now solved and CI'd https://github.com/ityonemo/zigler/pull/250
